import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define  the state for the forgot password feature
interface ForgotPasswordState {
    isEmailSent: boolean;
}

// Initial state for the forgot password feature
const initialState: ForgotPasswordState = {
    isEmailSent: false,
}

// Create a Redux slice for the forgot password feature
const forgotPasswordSlice = createSlice ({
    name: 'forgotPassword', // Name of the slice
    initialState,           // Initial state
    reducers: {
        // Action to set isEmailSent to true when the email is successfully sent
        setEmailSent: (state) => {
            state.isEmailSent = true;
        },
        // Action to clear the isEmailSent flag
        clearEmailSent: (state) => {
            state.isEmailSent = false;
        },
    },
});
// Export actions for use in forgot password component or other parts of the application
export const {setEmailSent, clearEmailSent} = forgotPasswordSlice.actions;
// Export the reducer function generated by createSlice
export default forgotPasswordSlice.reducer;