import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define  the state for the reset password feature
interface ResetPasswordState {
    isPasswordReset: boolean;
}

// Initial state for the reset password feature
const initialState: ResetPasswordState = {
    isPasswordReset: false,
}

// Create a Redux slice for the reset password feature
const resetPasswordSlice = createSlice ({
    name: 'resetPassword', // Name of the slice
    initialState,            // Initial state
    reducers: {
        // Action to set isPasswordReset to true when the password is successfully reset
        setPasswordReset: (state) => {
            state.isPasswordReset = true;
        },
        // Action to clear the isPasswordReset flag
        clearPasswordReset: (state) => {
            state.isPasswordReset = false;
        },
    },
});
// Export actions for use in password reset component or other parts of the application
export const {setPasswordReset, clearPasswordReset} = resetPasswordSlice.actions;
// Export the reducer function generated by createSlice
export default resetPasswordSlice.reducer;