import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the state for sign-up
interface SignUpState {
    user: {
        userName: string;
        email: string;
        isLoggedIn: boolean;
        _id: string;
    } | null;
}

// Initial state for sign-up
const initialState: SignUpState = {
    user: null,
};

// Create a Redux slice for sign-up
const signUpSlice = createSlice({
    name: 'signUp', // Name of the slice
    initialState, // Initial state
    reducers: {
        // Action to set user data after successful sign-up
        setUser: (state, action: PayloadAction<{userName: string; email: string; isLoggedIn: boolean; _id: string}>) => {
            state.user = action.payload;
        },
        // Action to clear user data in case of log out or other scenarios
        clearUser: (state) => {
            state.user = null;
        }
    }
});
// Export actions for use in signin component or other parts of the application
export const {setUser, clearUser} = signUpSlice.actions;
// Export the reducer function generated by createSlice
export default signUpSlice.reducer;